AceGenericBundle_index:
    pattern:  /
    defaults: { _controller: AceGenericBundle:Default:index }

AceGenericBundle_user:
    pattern:  /user/{user}
    defaults: { _controller: AceGenericBundle:Default:user }

AceGenericBundle_project:
    pattern:  /sketch:{id}
    defaults: { _controller: AceGenericBundle:Default:project }

AceGenericBundle_libraries:
    pattern: /libraries
    defaults: {_controller: AceGenericBundle:Default:libraries }

AceGenericBundle_boards:
    pattern: /boards
    defaults: {_controller: AceGenericBundle:Default:boards }
