AceExperimentalUserBundle_getcurrentuser:
    pattern:  /getcurrentuser
    defaults: { _controller: usercontroller:getCurrentUserAction }

AceExperimentalUserBundle_options:
    pattern:  /options
    defaults: { _controller: usercontroller:optionsAction }
    
AceExperimentalUserBundle_setoptions:
    pattern:  /setoptions
    defaults: { _controller: usercontroller:setoptionsAction }
    requirements:
        _method:   POST

AceExperimentalUserBundle_checkpass:
    pattern:  /checkpass
    defaults: { _controller: usercontroller:checkpassAction }
    requirements:
        _method:   POST

AceExperimentalUserBundle_checkmail:
    pattern:  /checkmail
    defaults: { _controller: usercontroller:checkmailAction }
    requirements:
        _method:   POST
