imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    translator:      { fallback: en }
    #translator:     ~
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: en 
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        site_name: "codebender"
# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database.host%
        port:     %database_port%
        dbname:   %database.name%
        user:     %database.user%
        password: %database.password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
#swiftmailer:
#    transport:	smtp
#    host:	localhost
#    username:	~
#    password:	~
#    port:	465
#    encryption:	tls
    #auth_mode:	~
    #spool:
        #type:                 file
        #path:                 %kernel.cache_dir%/swiftmailer/spool
    #sender_address:       ~
    #antiflood:
        #threshold:            99
        #sleep:                0
    #delivery_address:     ~
    #disable_delivery:     ~
    #logging:              %kernel.debug%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Ace\ExperimentalUserBundle\Entity\ExperimentalUser
#    service:
#        mailer: fos_user.mailer.twig_swift
#    from_email:
#        address:        girder@codebender.cc
#        sender_name:    Codebender Support
    registration:
#        confirmation:
#            enabled: true
#            email:
#               template: AceExperimentalUserBundle:User:resetting.email.twig
        form:
            type: ace_experimental_user_registration
#    resetting:
#        email:
#            template: AceExperimentalUserBundle:User:resetting.email.twig

doctrine_mongodb:
    connections:
        default:
            server:   mongodb://codebender:CODEb3nd3r!@ds031847.mongolab.com:31847/codebender
            options:
                connect: true
    default_database: codebender
    document_managers:
        default:
            auto_mapping: true

# my.foo.service:
#     class: Ace\FileBundle\Controller\ServiceController
#     arguments:
#         container: "@service_container"


