AceUserBundle:
    resource: "@AceUserBundle/Resources/config/routing.yml"
    prefix:   /

AceEditorBundle:
    resource: "@AceEditorBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: AceSecurityBundle:Security:login }

login_check:
    pattern:   /login_check

_security_logout:
    pattern:  /logout

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

