security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
#            algorithm: sha1
#            encode_as_base64: false
#            iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/list/*, roles: ROLE_USER }
        - { path: ^/edit/*, roles: ROLE_USER }
        - { path: ^/options/*, roles: ROLE_USER }
        - { path: ^/create/*, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }

    providers:
#        administrators:
#            entity: { class: AceUserBundle:User }
#        
        in_memory:
            users:
                user: { password: userpass, roles: [ 'ROLE_USER' ] }
                tzikis: { password: qwerty, roles: [ 'ROLE_USER' ] }
                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/*
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
            logout:
                path:   /logout
                target: /home
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    # access_control:
    #     - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
    #     - { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
