AceUtilitiesBundle_newproject:
    pattern:  /newproject
    defaults: { _controller: AceUtilitiesBundle:Default:newproject }
    requirements:
       _method:  POST

AceUtilitiesBundle_deleteproject:
   pattern:  /deleteproject/{id}
   defaults: { _controller: AceUtilitiesBundle:Default:deleteproject }

AceUtilitiesBundle_getprojectdescription:
   pattern:  /getprojectdescription/{id}
   defaults: { _controller: AceUtilitiesBundle:Default:getDescription }

AceUtilitiesBundle_setprojectdescription:
   pattern:  /setprojectdescription/{id}
   defaults: { _controller: AceUtilitiesBundle:Default:setDescription }
   requirements:
      _method:  POST

AceUtilitiesBundle_download:
  pattern:  /download/{id}
  defaults: { _controller: AceUtilitiesBundle:Default:download }

AceUtilitiesBundle_savecode:
  pattern:  /savecode/{id}
  defaults: { _controller: AceUtilitiesBundle:Default:saveCode }
  requirements:
     _method:  POST

AceUtilitiesBundle_createfile:
  pattern:  /createfile/{id}
  defaults: { _controller: AceUtilitiesBundle:Default:createFile }
  requirements:
    _method:  POST

AceUtilitiesBundle_deletefile:
  pattern:  /deletefile/{id}
  defaults: { _controller: AceUtilitiesBundle:Default:deleteFile }
  requirements:
    _method:  POST

AceUtilitiesBundle_compile:
  pattern:  /compile
  defaults: { _controller: AceUtilitiesBundle:Default:compile }
  requirements:
    _method:   POST
