parameters:
#    ace_security.example.class: Ace\SecurityBundle\Example

services:
#    ace_security.example:
#        class: %ace_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
