AceBlogBundle_blog:
    pattern:  /{page}
    defaults: { _controller: AceBlogBundle:Default:blog, page: "1" }

AceBlogBundle_blogRss:
    pattern:  /blogRss
    defaults: { _controller: AceBlogBundle:Default:blogRss }

AceBlogBundle_blognew:
    pattern:  /newblogpost
    defaults: { _controller: AceBlogBundle:Default:blog_new }

AceBlogBundle_viewpost:
    pattern:  /viewpost/{id}
    defaults: { _controller: AceBlogBundle:Default:viewpost, id: "0" }
