AceFileBundle_create:
    pattern:  /create
    defaults: { _controller: AceFileBundle:Default:create }

AceFileBundle_getTimestamp:
    pattern: /get_timestamp/{project_name}/{type}
    defaults: { _controller: AceFileBundle:Default:getTimestamp }

AceFileBundle_getMyCode:
    pattern:  /get_code/{project_name}
    defaults: { _controller: AceFileBundle:Default:getMyCode}

AceFileBundle_getMyEscapedCode:
    pattern:  /get_esc_code/{project_name}
    defaults: { _controller: AceFileBundle:Default:getMyEscapedCode}

AceFileBundle_getCode:
    pattern:  /get_code/{username}/{project_name}
    defaults: { _controller: AceFileBundle:Default:getCode}

AceFileBundle_getEscapedCode:
    pattern:  /get_esc_code/{username}/{project_name}
    defaults: { _controller: AceFileBundle:Default:getEscapedCode}

AceFileBundle_saveCode:
    pattern:  /save_code
    defaults: { _controller: AceFileBundle:Default:saveCode }

AceFileBundle_getMyHex:
    pattern:  /get_hex/{project_name}
    defaults: { _controller: AceFileBundle:Default:getMyHex}

# AceFileBundle_saveHex:
#     pattern:  /save_hex
#     defaults: { _controller: AceFileBundle:Default:saveHex }

AceFileBundle_saveHex:
    pattern:  /save_hex/{project_name}/{data}
    defaults: { _controller: AceFileBundle:Default:saveHex }

AceFileBundle_delete:
    pattern:  /delete/{project_name}
    defaults: { _controller: AceFileBundle:Default:delete }


AceFileBundle_getDescription:
    pattern:  /get_desc/{username}/{project_name}
    defaults: { _controller: AceFileBundle:Default:getDescription}

AceFileBundle_getMyDescription:
    pattern:  /get_desc/{project_name}
    defaults: { _controller: AceFileBundle:Default:getMyDescription}

AceFileBundle_saveDescription:
    pattern:  /save_desc
    defaults: { _controller: AceFileBundle:Default:saveDescription }

