AceEditorBundle_homepage:
    pattern:  /home
    defaults: { _controller: AceEditorBundle:Default:index }

AceEditorBundle_list:
    pattern:  /list
    defaults: { _controller: AceEditorBundle:Default:list }

AceEditorBundle_editor:
    pattern:  /edit/{filename}
    defaults: { _controller: AceEditorBundle:Default:edit, filename: default_text.txt }

AceEditorBundle_save:
    pattern:  /save/{filename}
    defaults: { _controller: AceEditorBundle:Default:save }
    
AceEditorBundle_options:
    pattern:  /options
    defaults: { _controller: AceEditorBundle:Default:options }
