AceEditorBundle_editor:
    pattern:  /edit/{project_name}
    defaults: { _controller: AceEditorBundle:Default:edit}

AceEditorBundle_compile:
    pattern:  /compile
    defaults: { _controller: AceEditorBundle:Default:compile }

AceEditorBundle_download:
    pattern:  /download/{username}/{project_name}/{type}
    defaults: { _controller: AceEditorBundle:Default:download, type: file }
    
AceEditorBundle_options:
    pattern:  /options
    defaults: { _controller: AceEditorBundle:Default:options }
    
AceEditorBundle_setoptions:
    pattern:  /setoptions
    defaults: { _controller: AceEditorBundle:Default:setoptions }

AceEditorBundle_checkpass:
    pattern:  /checkpass
    defaults: { _controller: AceEditorBundle:Default:checkpass }

AceEditorBundle_checkmail:
    pattern:  /checkmail
    defaults: { _controller: AceEditorBundle:Default:checkmail }

