AceUserBundle_getid:
    pattern:  /getid/{username}
    defaults: { _controller: usercontroller:getIdAction }

AceUserBundle_getcurrentuser:
    pattern:  /getcurrentuser
    defaults: { _controller: usercontroller:getCurrentUserAction }

AceUserBundle_options:
    pattern:  /options
    defaults: { _controller: usercontroller:optionsAction }
    
AceUserBundle_setoptions:
    pattern:  /setoptions
    defaults: { _controller: usercontroller:setoptionsAction }
    requirements:
        _method:   POST

AceUserBundle_checkpass:
    pattern:  /checkpass
    defaults: { _controller: usercontroller:checkpassAction }
    requirements:
        _method:   POST

AceUserBundle_checkmail:
    pattern:  /checkmail
    defaults: { _controller: usercontroller:checkmailAction }
    requirements:
        _method:   POST
