AceProjectBundle_create:
    pattern:  /create/{owner}/{name}/{description}
    defaults: { _controller: projectmanager:createAction }

AceProjectBundle_delete:
    pattern:  /delete/{id}
    defaults: { _controller: projectmanager:deleteAction }

AceProjectBundle_clone:
    pattern:  /clone/{owner}/{id}
    defaults: { _controller: projectmanager:cloneAction }

AceProjectBundle_rename:
    pattern:  /rename/{id}/{new_name}
    defaults: { _controller: projectmanager:renameAction }

AceProjectBundle_list:
    pattern:  /list/{owner}
    defaults: { _controller: projectmanager:listAction }

AceProjectBundle_getowner:
    pattern:  /getowner/{id}
    defaults: { _controller: projectmanager:getOwnerAction }

AceProjectBundle_getdescription:
    pattern:  /getdescription/{id}
    defaults: { _controller: projectmanager:getDescriptionAction }

AceProjectBundle_setdescription:
    pattern:  /setdescription/{id}/{description}
    defaults: { _controller: projectmanager:setDescriptionAction }

AceProjectBundle_listFiles:
    pattern:  /listfiles/{id}/
    defaults: { _controller: projectmanager:listFilesAction }

AceProjectBundle_createFile:
    pattern:  /createfile/{id}/{filename}/{code}
    defaults: { _controller: projectmanager:createFileAction }

AceProjectBundle_deleteFile:
    pattern:  /deletefile/{id}/{filename}
    defaults: { _controller: projectmanager:deleteFileAction }

AceProjectBundle_renameFile:
    pattern:  /renamefile/{id}/{filename}/{new_filename}
    defaults: { _controller: projectmanager:renameFileAction }

AceProjectBundle_getFile:
    pattern:  /getfile/{id}/{filename}
    defaults: { _controller: projectmanager:getFileAction }

AceProjectBundle_setFile:
    pattern:  /setfile/{id}/{filename}/{code}
    defaults: { _controller: projectmanager:setFileAction }

AceProjectBundle_search:
    pattern: /search/project/{token}
    defaults: { _controller: projectmanager:searchAction }

AceProjectBundle_searchName:
    pattern: /search/name/{token}
    defaults: { _controller: projectmanager:searchNameAction }

AceProjectBundle_searchDescription:
    pattern: /search/description/{token}
    defaults: { _controller: projectmanager:searchDescriptionAction }

AceProjectBundle_checkexists:
    pattern: /exists/{token}
    defaults: { _controller: projectmanager:checkExistsAction }
