AceProjectBundle_create:
    pattern:  /create/{owner}/{name}/{description}
    defaults: { _controller: projectmanager:createAction }

AceProjectBundle_delete:
    pattern:  /delete/{id}
    defaults: { _controller: projectmanager:deleteAction }

AceProjectBundle_list:
    pattern:  /list/{owner}
    defaults: { _controller: projectmanager:listAction }

AceProjectBundle_listFiles:
    pattern:  /listfiles/{id}/
    defaults: { _controller: projectmanager:listFilesAction }

AceProjectBundle_createFile:
    pattern:  /createfile/{id}/{filename}/{code}
    defaults: { _controller: projectmanager:createFileAction }

AceProjectBundle_deleteFile:
    pattern:  /deletefile/{id}/{filename}
    defaults: { _controller: projectmanager:deleteFileAction }

AceProjectBundle_getFile:
    pattern:  /getfile/{id}/{filename}
    defaults: { _controller: projectmanager:getFileAction }

AceProjectBundle_setFile:
    pattern:  /setfile/{id}/{filename}/{code}
    defaults: { _controller: projectmanager:setFileAction }

AceProjectBundle_getBinary:
    pattern:  /getbinary/{id}/{flags}
    defaults: { _controller: projectmanager:getBinaryAction }

AceProjectBundle_setBinary:
    pattern:  /setbinary/{id}/{flags}/{bin}
    defaults: { _controller: projectmanager:setBinaryAction }
