parameters:
#    ace_project.example.class: Ace\ProjectBundle\Example

services:
#    ace_project.example:
#        class: %ace_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
