parameters:
#    ace_owner.example.class: Ace\OwnerBundle\Example

services:
#    ace_owner.example:
#        class: %ace_owner.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
