parameters:
#    ace_misc.example.class: Ace\MiscBundle\Example

services:
#    ace_misc.example:
#        class: %ace_misc.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
