parameters:
#    ace_experimental_user.example.class: Ace\ExperimentalUserBundle\Example

services:
#    ace_experimental_user.example:
#        class: %ace_experimental_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    ace_experimental_user.experimental_provider:
        class: Ace\ExperimentalUserBundle\Security\Provider\ExperimentalProvider
        public: false
        arguments: ["@fos_user.user_manager"]

    ace_experimental_user.registration.form.type:
        class: Ace\ExperimentalUserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: ace_experimental_user_registration }
